# NumPy: Numerical Python



## El *ndarray* de NumPy

Supone el núcleo del paquete NumPy, encapsula **matrices de n dimensiones de tipos de datos homogéneos**.

- Los tipos deben ser homogéneos para que todos los elementos ocupen bloques del mismo tamaño en memoria
- Las matrices de NumPy facilitan las operaciones matemáticas en cantidades grandes de datos

In [18]:
shape = (3, 3)
ndarray_3d = np.random.randint(0, 10, size=shape)

print(ndarray_3d)

[[8 5 7]
 [1 1 9]
 [6 7 5]]


### Atributos importantes del numpy array:




| Atributos       | Descripción                                             |
|-----------------|---------------------------------------------------------|
| ndarray.shape    | Tupla con las dimensiones de la matriz                  |
| ndarray.ndim     | Número de dimensiones de la matriz                      |
| ndarray.dtype    | Tipo de los elementos en la matriz |
| ndarray.size     | Número de elementos en la matriz                        |
| ndarray.itemsize | Longitud de un elemento de matriz en bytes               |
| ndarray.nbytes   | Total de bytes consumidos por los elementos de la matriz |


### Creación de matrices 1D

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
# salto 2
np.arange(0, 10, 2, dtype=int)

array([0, 2, 4, 6, 8])

In [23]:
# decreciente
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [25]:
# empieza en 2, hasta 3 (sin incluir), de 0,1 en 0.1
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

### Creación de matrices 2D

In [26]:
# matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# diagonal
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
# creación de una array "a mano"
matrix = np.array([[1, 2],
                   [3, 4]])

print(matrix)

[[1 2]
 [3 4]]


In [33]:
# matriz 3x6 llena de ceros
np.zeros([3, 6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
# lo mismo pero llena de unos
np.ones([3, 6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
# números aleatorios, dimension N*M

N = 3
M = 4

matrix = np.random.randint(0, 10, size=(N, M))

print(matrix)

[[8 4 3 7]
 [7 4 2 2]
 [5 2 0 1]]


## Operaciones con NumPy arrays

- Operaciones aritméticas elemento a elemento (suma, resta, multiplicación, exponente, división...)
- Operaciones lógicas elemento a elemento
- Concatenación
- Producto de matrices (dot product)
- Matriz inversa
- Matriz traspuesta
- generación de elementos pseudoaleatorios

In [49]:
# suma
arr1 = np.array([[1, 3], [2, 4]])
arr2 = np.array([[5, 7], [6, 8]])
arr1 + arr2

array([[ 6, 10],
       [ 8, 12]])

In [50]:
# resta
arr2 - arr1

array([[4, 4],
       [4, 4]])

In [51]:
# multiplicación
arr1 = np.array([[1., 3., 5.], [2., 4., 6]])
arr2 = np.array([[7., 9., 11.], [8., 10., 12.]])
arr1 * arr2

array([[ 7., 27., 55.],
       [16., 40., 72.]])

In [52]:
# división
arr2 / arr1

array([[7. , 3. , 2.2],
       [4. , 2.5, 2. ]])

In [54]:
# exponente (realmente raíz cuadrada)
arr1 ** 0.5

array([[1.        , 1.73205081, 2.23606798],
       [1.41421356, 2.        , 2.44948974]])

In [72]:
# operaciones lógicas
arr2 > arr1

array([[ True,  True],
       [ True,  True]])

In [63]:
# producto de matrices
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

dot = np.dot(arr1, arr2)

print(dot)

[[19 22]
 [43 50]]


In [64]:
# inversa
inv = np.linalg.inv(arr1)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
# comprobación
np.round(np.dot(arr1, inv), 2)

array([[1., 0.],
       [0., 1.]])

In [69]:
# trasposición
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

# método 1: atributo T
transpuesta_t = mat.T

# método 2: función np.transpose()
transpuesta_transpose = np.transpose(mat)

In [71]:
# generación de matrices pseudoaleatorias
samples = np.random.normal(size=(4, 4))       # distribución normal
samples

array([[-0.37047967,  0.23287305,  0.22638249, -1.06615779],
       [ 0.28687391,  1.19864961,  0.37074287, -0.56669186],
       [-1.95719923,  1.33640966,  0.11049868,  0.42556371],
       [ 1.01106356,  2.37903664,  0.52509279,  0.06387236]])

### Concatenación
- axis=1: horizontalmente
- axis=0: verticalmente

In [42]:
# axis=1
# equivalente a np.hstack
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [43]:
# axis=0
# equivalente a np.vstack
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Ventajas de Numpy

NumPy es ampliamente utilizada en el ámbito de la computación científica en Python.

- NumPy almacena internamente los datos en bloques de memoria contiguos
- Está implementada en C
- Las matrices de NumPy, por tanto, emplean menor cantidad de memoria

Por este motivo, es óptima para operaciones con grandes volúmenes de datos.
Vamos a demostrar por qué supone una ventaja usar sus funciones en lugar de las de Python:

## 1. Velocidad de cálculo y sencillez de implementación

### Producto de matrices O(n²) con Python vanilla


Para facilitar las cosas, definiremos una función que multiplica matrices en python:

In [5]:
def matrix_multiply_python(A, B):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(B[0])):
            element = 0
            for k in range(len(B)):
                element += A[i][k] * B[k][j]
            row.append(element)
        result.append(row)
    return result

In [ ]:
def generate_random_matrix(rows, cols):
    return [[random.random() for _ in range(cols)] for _ in range(rows)]

matrix_a = generate_random_matrix(100, 100)  # matriz 1000x1000
matrix_b = generate_random_matrix(100, 100)  # matriz 1000x1000

Producto de matrices 100x100

In [76]:
import time, random

# medida de tiempo
start_time = time.time()
result_python = matrix_multiply_python(matrix_a, matrix_b)
end_time = time.time()

elapsed_time = end_time - start_time

print(f"[⌛] Tiempo de ejecución (100x100): {elapsed_time} segundos")


[⌛] Tiempo de ejecución (100x100): 0.14042067527770996 segundos


... ¿Y si aumentamos el tamaño a 1000x1000??

In [80]:
matrix_c = generate_random_matrix(1000, 1000)  # matriz 1000x1000
matrix_d = generate_random_matrix(1000, 1000)  # matriz 1000x1000

In [79]:
start_time = time.time()
result_python = matrix_multiply_python(matrix_c, matrix_d)
end_time = time.time()

elapsed_time = end_time - start_time

print(f"[⌛] Tiempo de ejecución (1000x1000): {elapsed_time} segundos")

KeyboardInterrupt: 

Resultado: 15 líneas de código y unos 100000 años de tiempo de ejecución.

### Producto de matrices O(n²) con NumPy


No sólo es más sencillo de implementar, sino miles de veces más rápido

In [81]:
import numpy as np

def matrix_multiply_numpy(A, B):
    return np.dot(A, B)

# declaración de matrices
matrix_a = np.random.rand(1000, 1000)
matrix_b = np.random.rand(1000, 1000)

# medida de tiempo
start_time = time.time()
result_numpy = matrix_multiply_numpy(matrix_a, matrix_b)
end_time = time.time()

elapsed_time = end_time - start_time


print(f"[⌛] Tiempo de ejecución: {elapsed_time} segundos")


[⌛] Tiempo de ejecución: 0.06160593032836914 segundos


Resultado: 5 líneas de código y una fracción de segundo.