In [ ]:
import numpy as np
import pandas as pd

# Ejercicios de NumPy y pandas

Estos ejercicios están pensados para que probéis de primera mano las capacidades de las librerías NumPy y pandas.

## Ejercicios de NumPy

### 1 - Creación de arrays

a) Crea un array vacío en numpy de dimensiones 3×6

In [ ]:
# SOL 1a


[[6.91372767e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


b) Repite el apartado a, pero llénalo con un número, como por ejemplo el `0`.

In [ ]:
# SOL 1b


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### 2 - Comprobación de valores en un array

Dado el array `arr`:

In [ ]:
arr = np.array([[5, 2, 0],
                [4, 3, 7]])

a) Comprueba con `numpy` si contiene el número 6

In [ ]:
# SOL 2a


False


b) Comprueba con `numpy` si contiene el número 4

In [ ]:
# SOL 2b


True


### 3 - Operaciones con numpy arrays

a) Reduce la siguiente matriz (array de 2 dimensiones) a una dimensión:

In [ ]:
mat = np.array([[2, 3], [4, 5]])
print(f"Array bidimensional:\n {mat}\n")

# SOL 3a


Array bidimensional:
 [[2 3]
 [4 5]]

Array unidimensional:
 [2 3 4 5]


b) Dados los vectores (arrays de 1 dimensión) `v_a` y `v_b`, calcula, **SIN USAR BUCLES**:
- `v_a` + `v_b` (elemento a elemento)
- `v_a` * `v_b` (elemento a elemento)
- Su producto escalar (dot product)   

In [ ]:
v_a = np.array([6, 9, 12])
v_b = np.array([8, 5, 2])

# SOL 3b
suma =              # tu solución para la suma
resta =             # tu solución para la resta
escalar =           # tu solución para el producto escalar

print(f"[+] Suma: \t{suma}\n[-] Resta: \t{resta} \n[·] Escalar: \t{escalar}")

[+] Suma: 	[14 14 14]
[-] Resta: 	[-2  4 10] 
[·] Escalar: 	117


## Ejercicios de pandas

Trabajaremos sobre un ejemplo de `DataFrame` que contiene datos sobre pilotos de fórmula 1.

Contamos con los siguientes datos:

|   Driver Name   | Number of Victories |  Country   |
|:---------------:|:-------------------:|:----------:|
|    Hamilton     |         103         |     UK     |
|   Schumacher    |         91          |  Germany   |
|    Raikkonen    |         26          |  Finland   |
|     Alonso      |         32          |   Spain    |
|     Vettel      |         53          |  Germany   |
|      Sainz      |         2           |   Spain    |
|    Hakkinen     |         20          |  Finland   |
|      Senna      |         41          |  Brazil    |
|   Verstappen    |         54          |Netherlands|
|   Fittipaldi    |         14          |  Brazil    |

### 1 - Creación de DataFrames

Empezaremos creando un dataframe sobre el que operar fijándonos en el DataFrame del ejemplo anterior.

Dada la siguiente lista bidimensional (matriz) y el array de nombres de columnas, crea el DataFrame mencionado anteriormente con `pandas`:

In [ ]:
drivers = [['Hamilton', 103, 'UK'], ['Schumacher', 91, 'Germany'],
           ['Raikkonen', 26, 'Finland'], ['Alonso', 32, 'Spain'],
           ['Vettel', 53, 'Germany'], ['Sainz', 2, 'Spain'],
           ['Hakkinen', 20, 'Finland'], ['Senna', 41, 'Brazil'],
           ['Verstappen', 54, 'Netherlands'], ['Fittipaldi', 14, 'Brazil'],     # Sí, Fittipaldi existe
           [None, None, None], ['Sainz', 2, 'Spain']]

column_names = ['Driver Name', 'Number of Victories', 'Country']


# SOL pd1
df = pd.DataFrame(None)        # cambia None por tu solución
df

Driver Name  Number of Victories      Country
0     Hamilton                103.0           UK
1   Schumacher                 91.0      Germany
2    Raikkonen                 26.0      Finland
3       Alonso                 32.0        Spain
4       Vettel                 53.0      Germany
5        Sainz                  2.0        Spain
6     Hakkinen                 20.0      Finland
7        Senna                 41.0       Brazil
8   Verstappen                 54.0  Netherlands
9   Fittipaldi                 14.0       Brazil
10        None                  NaN         None
11       Sainz                  2.0        Spain

### 2 - Selección de filas basada en condiciones

- *Anotación: puedes obtener los resultados de estos apartados en el formato que prefieras, no importa si es array o dataframe*

a) ¿Qué piloto tiene el mayor número de victorias? ¿Y el menor?

- *Pista: puedes usar los métodos idxmax e idxmin*




In [ ]:
# SOL 2a


El piloto con el mayor número de victorias es: Hamilton
El piloto con el menor número de victorias es: Sainz


b) Obtén los pilotos con más de 20 victorias.

In [1]:
# SOL 2b


NameError: name 'df' is not defined

c) ¿Cuántos pilotos finlandeses hay?

In [2]:
# SOL 2c


NameError: name 'df' is not defined

### 3 - Una pequeña introducción a limpieza de datos

Vaya... Parece que se han colado valores nulos en nuestro DataFrame. De esta forma no podremos operar con él en el futuro, vamos a hacer una pequeña limpieza en dos pasos.


*Importante: Esto es un pequeño adelanto del tema de preprocesamiento, así que os daremos alguna pista*

a) Empecemos eliminando los valores nulos por ser los más problemáticos. Podríamos usar el método `dropna` de pandas.

In [ ]:
# SOL 2a


Driver Name  Number of Victories      Country
0     Hamilton                103.0           UK
1   Schumacher                 91.0      Germany
2    Raikkonen                 26.0      Finland
3       Alonso                 32.0        Spain
4       Vettel                 53.0      Germany
5        Sainz                  2.0        Spain
6     Hakkinen                 20.0      Finland
7        Senna                 41.0       Brazil
8   Verstappen                 54.0  Netherlands
9   Fittipaldi                 14.0       Brazil
11       Sainz                  2.0        Spain

b) Ahora queda una pregunta... ¿Hace falta que el número de victorias tenga decimales? No se puede ganar media carrera... Como es un poco difícil de mirar, podríamos convertirlo a enteros.

De esta manera podemos ilustrar una gran comodidad que ofrece pandas: cambiar de tipo una columna entera (en el futuro, es posible que os encontréis columnas que vienen en un formato que no es, por ejemplo números en forma de string).

In [ ]:
# Este os lo damos hecho como ejemplo

df['Number of Victories'] = df['Number of Victories'].astype(int)

df

<ipython-input-34-bf89bd2e6872>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Number of Victories'] = df['Number of Victories'].astype(int)


Driver Name  Number of Victories      Country
0     Hamilton                  103           UK
1   Schumacher                   91      Germany
2    Raikkonen                   26      Finland
3       Alonso                   32        Spain
4       Vettel                   53      Germany
5        Sainz                    2        Spain
6     Hakkinen                   20      Finland
7        Senna                   41       Brazil
8   Verstappen                   54  Netherlands
9   Fittipaldi                   14       Brazil
11       Sainz                    2        Spain

¡Ya está! Nuestro dataframe es legible y podemos trabajar con él porque no contiene valores nulos.